# оставил композ только для локальной разработки.
# В проде использую makefile с отдельными командами для более точной настройки
version: "4"

services:
  bot:
    container_name: bot
    build: .
    ports:
      - "5000:5000"
    env_file:
      - docker.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always
    command: sh -c "alembic upgrade head && python -m bot"
    networks:
      - bot-network

  postgres:
    image: postgres:15
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${PG_DB} -U ${PG_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB}
    restart: always
    networks:
      - bot-network


  redis:
    image: redis
    restart: always
    networks:
      - bot-network


networks:
  bot-network:
    driver: bridge