"""user custom timezone

Revision ID: 8b460a97e198
Revises: b9f7254dcbf7
Create Date: 2024-05-11 13:37:01.080804

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8b460a97e198"
down_revision: Union[str, None] = "b9f7254dcbf7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("user_id", sa.Integer(), nullable=False))
    op.add_column("task", sa.Column("timezone", sa.String(), nullable=True))
    op.create_foreign_key(
        "fk_task", "task", "user", ["user_id"], ["user_id"], ondelete="cascade"
    )
    op.add_column("user", sa.Column("timezone", sa.String(), nullable=True))
    op.drop_column("user", "username")
    op.drop_column("user", "last_name")
    op.drop_column("user", "first_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("first_name", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "user", sa.Column("last_name", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "user", sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_column("user", "timezone")
    op.drop_constraint("fk_task", "task", type_="foreignkey")
    op.drop_column("task", "timezone")
    op.drop_column("task", "user_id")
    # ### end Alembic commands ###
